project:
  type: website

website:
  title: "wiki cruz"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - SOBRE GIT & GI-HUB.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



