project:
  type: website

website:
  title: CruzMartinez

  repo-url: https://github.com/leonpurple/wikicruz
  repo-actions: [edit, issue]

  navbar:
    background: primary
    style: "floating"
    search: true
    
    left:
           - text: Design Patterns
             file: index.qmd
           - sidebar:aboutgit
           - sidebar:aboutgithub
           - sidebar:aboutuml
            
  sidebar:
    - id: "aboutgit" 
      title: "Git" 
     # border: true

    - id: "aboutgithub" 
      title: "Git Hub"

    - id: "aboutuml"
      title: "UML"


















      
       
         
      
        
        
    
  page-footer: 
    background: dark
    left: "[Magazine CruzMartinez](https://github.com/leonpurple/wikicruz)" 
    center: "" 
    right: 
      - icon: github
        href: https://github.com/leonpurple/wikicruz/
       
        
    

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



