project:
  type: website

website:
  title: Welcome ComboBackend

  repo-url: https://github.com/leonpurple/wikicruz
  repo-actions: [edit, issue]

  navbar:
    background: dark
    style: "floating"
    search: true
    
    right:
           - text: Home #HOME
             file: index.qmd
           - sidebar:designpatterns  
           - sidebar:aboutgit
           #- sidebar:aboutgithub
           #- sidebar:aboutuml
           - sidebar:programmingparadigms #ADD FEATURES
           - sidebar:vocabulary
           #- sidebar:vocabulary-regulars-verbs

  #INIT NAV          
  sidebar:

      #ABOUTGIT
    - id: "aboutgit" 
      title: "Git" 
      border: true
      background: none
      style: "floating"
      contents:
        - text: "Git"
        - text: "---"
        - section: "flow Git"
          contents:
          - aboutgit/aboutgit.qmd


        
      #ABOUT DesignPatterns-HUB
    - id: "designpatterns" 
      title: "Desing Patterns"  
      border: true
      background: none
      style: "floating"
      contents:
        - text: "Desing Patterns"
        - text: "---"
        - section: "Super Info" 
          contents:
          - designpatterns/designpatterns.qmd  
        
      #ABOUT GIT-HUB
    - id: "aboutgithub" 
      title: "Git Hub"

      #UML
    - id: "aboutuml"
      title: "UML"

      #PROGRAMMING PARDIGMS
    - id: "programmingparadigms"
      title: "Programming Paradigms"  
      border: true
      background: none
      style: "floating"
      contents:
        - text: "Programming Paradigms" 
        - text: "---" 
        - section: "Super Info "
          contents:
          - programmingparadigms/programmingparadigms.qmd

      #VOCABULARY
    - id: "vocabulary"
      title: "vocabulary"  
      border: true
      background: none
      style: "floating"
      contents:
        - text: "Vocabulary" 
        - text: "---" 
        - section: "Super Info "
          contents:
          - vocabulary/vocabulary.qmd    




















      
       
         
      
        
        
    
  page-footer: 
    background: dark
    left: "[Magazine CruzMartinez](https://github.com/leonpurple/wikicruz)" 
    center: "" 
    right: 
      - icon: github
        href: https://github.com/leonpurple/wikicruz/
       
        
    

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

